// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDzDfXQeUKAoCF9KNQNmMg__MDRRBF-M0',
    appId: '1:168258862337:web:1589536f9b8f15e6ce2f00',
    messagingSenderId: '168258862337',
    projectId: 'maple-5897b',
    authDomain: 'maple-5897b.firebaseapp.com',
    storageBucket: 'maple-5897b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_V9T-3Rxmqnda70h_tBUO3ZYsqoDWMig',
    appId: '1:168258862337:android:187848d17e5f2c20ce2f00',
    messagingSenderId: '168258862337',
    projectId: 'maple-5897b',
    storageBucket: 'maple-5897b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo2yJXJMKbPBjJVME8igGy0gVDx5SB3fU',
    appId: '1:168258862337:ios:05738ab9aa3699a9ce2f00',
    messagingSenderId: '168258862337',
    projectId: 'maple-5897b',
    storageBucket: 'maple-5897b.appspot.com',
    iosClientId:
        '168258862337-s0d85i6upeer1bb78b99cjh7gfrn2cpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.maple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo2yJXJMKbPBjJVME8igGy0gVDx5SB3fU',
    appId: '1:168258862337:ios:05738ab9aa3699a9ce2f00',
    messagingSenderId: '168258862337',
    projectId: 'maple-5897b',
    storageBucket: 'maple-5897b.appspot.com',
    iosClientId:
        '168258862337-s0d85i6upeer1bb78b99cjh7gfrn2cpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.maple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDzDfXQeUKAoCF9KNQNmMg__MDRRBF-M0',
    appId: '1:168258862337:web:8b36346d159d1d35ce2f00',
    messagingSenderId: '168258862337',
    projectId: 'maple-5897b',
    authDomain: 'maple-5897b.firebaseapp.com',
    storageBucket: 'maple-5897b.appspot.com',
  );
}
